apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #container-port
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db