apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
      project: roboshop
      tier: db 
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: "brahmamdevops/mysql:{{ .Values.statefulset.imageVersion }}"
        args:
        - "--ignore-db-dir=lost+found"
        envFrom:
        - configMapRef:
            name: mysql
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 2Gi


