apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
      project: roboshop
      tier: db 
  serviceName: "redis"
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: "redis:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi


